export const formations = [
  {
    id: "4-4-2",
    slots: [
      { positionKey: "GK", role: "GK", x: 50, y: 92 },
      { positionKey: "LB", role: "DEF", x: 20, y: 72 },
      { positionKey: "LCB", role: "DEF", x: 40, y: 72 },
      { positionKey: "RCB", role: "DEF", x: 60, y: 72 },
      { positionKey: "RB", role: "DEF", x: 80, y: 72 },
      { positionKey: "LM", role: "MID", x: 20, y: 50 },
      { positionKey: "LCM", role: "MID", x: 40, y: 50 },
      { positionKey: "RCM", role: "MID", x: 60, y: 50 },
      { positionKey: "RM", role: "MID", x: 80, y: 50 },
      { positionKey: "LS", role: "ATT", x: 40, y: 26 },
      { positionKey: "RS", role: "ATT", x: 60, y: 26 },
    ],
  },
  {
    id: "3-5-2",
    slots: [
      { positionKey: "GK", role: "GK", x: 50, y: 92 },
      { positionKey: "LCB", role: "DEF", x: 30, y: 72 },
      { positionKey: "CB", role: "DEF", x: 50, y: 72 },
      { positionKey: "RCB", role: "DEF", x: 70, y: 72 },
      { positionKey: "LWB", role: "MID", x: 15, y: 55 },
      { positionKey: "LCM", role: "MID", x: 35, y: 50 },
      { positionKey: "CAM", role: "MID", x: 50, y: 40 },
      { positionKey: "RCM", role: "MID", x: 65, y: 50 },
      { positionKey: "RWB", role: "MID", x: 85, y: 55 },
      { positionKey: "LS", role: "ATT", x: 42, y: 25 },
      { positionKey: "RS", role: "ATT", x: 58, y: 25 },
    ],
  },
  {
    id: "4-3-3",
    slots: [
      { positionKey: "GK", role: "GK", x: 50, y: 92 },
      { positionKey: "LB", role: "DEF", x: 20, y: 72 },
      { positionKey: "LCB", role: "DEF", x: 40, y: 72 },
      { positionKey: "RCB", role: "DEF", x: 60, y: 72 },
      { positionKey: "RB", role: "DEF", x: 80, y: 72 },
      { positionKey: "LCM", role: "MID", x: 35, y: 52 },
      { positionKey: "CM", role: "MID", x: 50, y: 48 },
      { positionKey: "RCM", role: "MID", x: 65, y: 52 },
      { positionKey: "LW", role: "ATT", x: 20, y: 28 },
      { positionKey: "ST", role: "ATT", x: 50, y: 24 },
      { positionKey: "RW", role: "ATT", x: 80, y: 28 },
    ],
  },
];
